env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    - secure: "cn1+7McUqDa+GLXnLqD/+LHQt1rgCaKUMuVsj//m5fMHf6xaYyWiit3nnhbg0iyhlcjX3+J2Fl3XnH6HRsZTlU53NLL2A1K2Ge9deMo/ZBp9IN+OhkjFFaSU5bAL9ttllkDOnzZmLf/dZJgBvRNXma3j0GeFEnSb66PXsDXjxQY="
    # Note: Set our configure command here, rather than in the addon section,
    # as the Coverity addon does not handle this properly via
    # build_command_prepend, as it is documented to do.  Looks like the
    # necessary/expected COVERITY_SCAN_BUILD_COMMAND_PREPEND environment
    # is not populated by the downloaded ravisci_build_coverity_scan.sh script.
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="./configure --enable-ctrls --enable-dso --enable-facl --enable-memcache --enable-nls --enable-pcre --with-modules=mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_passwd:mod_sftp:mod_sftp_sql:mod_sftp_pam:mod_tls:mod_tls_fscache:mod_tls_shmcache:mod_tls_memcache:mod_ban:mod_copy:mod_ctrls_admin:mod_deflate:mod_dnsbl:mod_dynmasq:mod_exec:mod_facl:mod_geoip:mod_ifversion:mod_ldap:mod_load:mod_log_forensic:mod_quotatab:mod_quotatab_file:mod_quotatab_sql:mod_radius:mod_readme:mod_rewrite:mod_shaper:mod_site_misc:mod_snmp:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_digest:mod_auth_otp:mod_statcache:mod_ifsession"

language: c

compiler:
  - gcc
  - clang

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  # Need to add other repos for e.g. libsodium
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
  - echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-get update -qq
  # for mod_lang
  - sudo apt-get install -y gettext
  # for xattr support
  - sudo apt-get install -y libattr1-dev
  # for mod_cap
  - sudo apt-get install -y libcap-dev
  # for mod_geoip
  - sudo apt-get install -y libgeoip-dev
  # for mod_ldap
  - sudo apt-get install -y libldap2-dev libsasl2-dev
  # for memcache support
  - sudo apt-get install -y libmemcached-dev
  # for mod_sql_mysql
  - sudo apt-get install -y libmysqlclient-dev
  # for PAM support
  - sudo apt-get install -y libpam-dev
  # for mod_sql_postgres
  - sudo apt-get install -y libpq-dev
  # for OpenSSL support
  - sudo apt-get install -y libssl-dev
  # for Sodium support
  - sudo apt-get install -y --force-yes libsodium-dev
  # for mod_sql_sqlite
  - sudo apt-get install -y libsqlite3-dev sqlite3
  # for PCRE support
  - sudo apt-get install -y libpcre3-dev

addons:
  coverity_scan:
    project:
      name: "proftpd/proftpd"
      description: "Build submitted via Travis CI"
    notification_email: tj@castaglia.org
    build_command: "make"
    branch_pattern: coverity-travis
